// 自動生成 by fetch_stocks.py
// 最後更新: 2026-03-30 20:22:46
// 共 2 週歷史資料 — 請勿手動編輯

const STOCK_DATA = [
  {
    "date": "2026-03-30",
    "valueStocks": [
      {
        "ticker": "CMCSA",
        "name": "康卡斯特",
        "pe_ratio": 5.26,
        "current_price": 28.33,
        "low_52w": 24.13,
        "distance_from_low": 17.4,
        "market_cap": 103.2,
        "daily_volume": 49.7,
        "sector": "電信",
        "dividend_yield": 4.66,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "CHTR",
        "name": "Charter Communications",
        "pe_ratio": 6.05,
        "current_price": 219.14,
        "low_52w": 180.38,
        "distance_from_low": 21.5,
        "market_cap": 27.8,
        "daily_volume": 1.6,
        "sector": "電信",
        "dividend_yield": 0.0,
        "risk_level": "中高",
        "recommendation": ""
      },
      {
        "ticker": "APA",
        "name": "APA公司",
        "pe_ratio": 11.13,
        "current_price": 44.39,
        "low_52w": 13.58,
        "distance_from_low": 226.9,
        "market_cap": 15.7,
        "daily_volume": 9.9,
        "sector": "能源",
        "dividend_yield": 2.25,
        "risk_level": "高",
        "recommendation": ""
      },
      {
        "ticker": "ALL",
        "name": "Allstate公司",
        "pe_ratio": 5.32,
        "current_price": 202.71,
        "low_52w": 176.0,
        "distance_from_low": 15.2,
        "market_cap": 52.6,
        "daily_volume": 1.5,
        "sector": "保險",
        "dividend_yield": 2.13,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "EIX",
        "name": "Edison International",
        "pe_ratio": 6.09,
        "current_price": 70.3,
        "low_52w": 47.73,
        "distance_from_low": 47.3,
        "market_cap": 27.1,
        "daily_volume": 4.1,
        "sector": "公用事業",
        "dividend_yield": 4.99,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "VZ",
        "name": "Verizon",
        "pe_ratio": 12.39,
        "current_price": 50.31,
        "low_52w": 38.39,
        "distance_from_low": 31.0,
        "market_cap": 212.2,
        "daily_volume": 29.4,
        "sector": "電信",
        "dividend_yield": 5.63,
        "risk_level": "低",
        "recommendation": "優先推薦"
      },
      {
        "ticker": "COP",
        "name": "ConocoPhillips",
        "pe_ratio": 21.04,
        "current_price": 133.8,
        "low_52w": 79.88,
        "distance_from_low": 67.5,
        "market_cap": 163.5,
        "daily_volume": 13.0,
        "sector": "能源",
        "dividend_yield": 2.51,
        "risk_level": "中低",
        "recommendation": "推薦買入"
      },
      {
        "ticker": "XOM",
        "name": "埃克森美孚",
        "pe_ratio": 25.52,
        "current_price": 170.99,
        "low_52w": 97.8,
        "distance_from_low": 74.8,
        "market_cap": 712.5,
        "daily_volume": 25.3,
        "sector": "能源",
        "dividend_yield": 2.41,
        "risk_level": "中低",
        "recommendation": ""
      },
      {
        "ticker": "PFE",
        "name": "Pfizer",
        "pe_ratio": 19.88,
        "current_price": 27.04,
        "low_52w": 20.92,
        "distance_from_low": 29.3,
        "market_cap": 153.8,
        "daily_volume": 45.0,
        "sector": "醫療",
        "dividend_yield": 6.36,
        "risk_level": "中低",
        "recommendation": ""
      },
      {
        "ticker": "MRK",
        "name": "Merck",
        "pe_ratio": 16.41,
        "current_price": 119.63,
        "low_52w": 73.31,
        "distance_from_low": 63.2,
        "market_cap": 295.8,
        "daily_volume": 10.8,
        "sector": "醫療",
        "dividend_yield": 2.84,
        "risk_level": "低",
        "recommendation": "優先推薦"
      }
    ],
    "momentumStocks": [
      {
        "ticker": "COP",
        "name": "ConocoPhillips",
        "five_day_return": 5.4,
        "rsi_14": 84.2,
        "roc_14": 14.3,
        "roc_21": 20.9,
        "status": "超買接近",
        "outlook": "謹慎",
        "trend": "高於所有均線"
      },
      {
        "ticker": "MRK",
        "name": "Merck",
        "five_day_return": 4.8,
        "rsi_14": 65.9,
        "roc_14": 2.9,
        "roc_21": 1.0,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "CSCO",
        "name": "Cisco",
        "five_day_return": 2.9,
        "rsi_14": 63.3,
        "roc_14": 4.9,
        "roc_21": 2.3,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "ABBV",
        "name": "AbbVie",
        "five_day_return": 2.1,
        "rsi_14": 24.4,
        "roc_14": -7.9,
        "roc_21": -6.8,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "低於主要均線"
      },
      {
        "ticker": "AMD",
        "name": "AMD",
        "five_day_return": 0.3,
        "rsi_14": 49.5,
        "roc_14": -0.3,
        "roc_21": -0.8,
        "status": "偏弱",
        "outlook": "觀望",
        "trend": "高於200MA"
      },
      {
        "ticker": "AMGN",
        "name": "Amgen",
        "five_day_return": 0.3,
        "rsi_14": 20.4,
        "roc_14": -7.5,
        "roc_21": -8.1,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "高於200MA"
      },
      {
        "ticker": "NKE",
        "name": "Nike",
        "five_day_return": -1.9,
        "rsi_14": 23.3,
        "roc_14": -9.1,
        "roc_21": -19.1,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "低於主要均線"
      },
      {
        "ticker": "GILD",
        "name": "吉利德科學",
        "five_day_return": -2.2,
        "rsi_14": 19.8,
        "roc_14": -7.9,
        "roc_21": -6.1,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "高於200MA"
      },
      {
        "ticker": "LLY",
        "name": "禮來",
        "five_day_return": -3.1,
        "rsi_14": 15.4,
        "roc_14": -12.9,
        "roc_21": -14.1,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "低於主要均線"
      },
      {
        "ticker": "DHR",
        "name": "Danaher",
        "five_day_return": -4.1,
        "rsi_14": 27.5,
        "roc_14": -8.7,
        "roc_21": -13.3,
        "status": "超賣",
        "outlook": "觀望",
        "trend": "低於主要均線"
      }
    ]
  },
  {
    "date": "2025-11-10",
    "valueStocks": [
      {
        "ticker": "CMCSA",
        "name": "康卡斯特",
        "pe_ratio": 4.55,
        "current_price": 34.15,
        "low_52w": 30.8,
        "distance_from_low": 10.9,
        "market_cap": 125.8,
        "daily_volume": 25.3,
        "sector": "電信",
        "dividend_yield": 2.1,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "CHTR",
        "name": "Charter Communications",
        "pe_ratio": 5.78,
        "current_price": 58.37,
        "low_52w": 45.2,
        "distance_from_low": 29.2,
        "market_cap": 55.6,
        "daily_volume": 5.8,
        "sector": "電信",
        "dividend_yield": 2.5,
        "risk_level": "中高",
        "recommendation": ""
      },
      {
        "ticker": "APA",
        "name": "APA公司",
        "pe_ratio": 5.91,
        "current_price": 21.64,
        "low_52w": 19.8,
        "distance_from_low": 9.3,
        "market_cap": 7.74,
        "daily_volume": 4.2,
        "sector": "能源",
        "dividend_yield": 0.0,
        "risk_level": "高",
        "recommendation": ""
      },
      {
        "ticker": "ALL",
        "name": "Allstate公司",
        "pe_ratio": 6.69,
        "current_price": 45.2,
        "low_52w": 42.1,
        "distance_from_low": 7.3,
        "market_cap": 35.2,
        "daily_volume": 8.9,
        "sector": "保險",
        "dividend_yield": 3.2,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "EIX",
        "name": "Edison International",
        "pe_ratio": 7.09,
        "current_price": 28.5,
        "low_52w": 26.4,
        "distance_from_low": 8.0,
        "market_cap": 18.9,
        "daily_volume": 6.2,
        "sector": "公用事業",
        "dividend_yield": 4.1,
        "risk_level": "中",
        "recommendation": ""
      },
      {
        "ticker": "VZ",
        "name": "Verizon",
        "pe_ratio": 10.22,
        "current_price": 42.1,
        "low_52w": 39.5,
        "distance_from_low": 6.6,
        "market_cap": 185.3,
        "daily_volume": 17.3,
        "sector": "電信",
        "dividend_yield": 6.16,
        "risk_level": "低",
        "recommendation": "優先推薦"
      },
      {
        "ticker": "COP",
        "name": "ConocoPhillips",
        "pe_ratio": 9.8,
        "current_price": 58.75,
        "low_52w": 55.8,
        "distance_from_low": 5.4,
        "market_cap": 75.6,
        "daily_volume": 7.5,
        "sector": "能源",
        "dividend_yield": 2.8,
        "risk_level": "中低",
        "recommendation": "推薦買入"
      },
      {
        "ticker": "XOM",
        "name": "埃克森美孚",
        "pe_ratio": 8.5,
        "current_price": 115.2,
        "low_52w": 108.1,
        "distance_from_low": 6.6,
        "market_cap": 454.1,
        "daily_volume": 12.0,
        "sector": "能源",
        "dividend_yield": 3.5,
        "risk_level": "中低",
        "recommendation": ""
      },
      {
        "ticker": "PFE",
        "name": "Pfizer",
        "pe_ratio": 9.2,
        "current_price": 28.4,
        "low_52w": 26.1,
        "distance_from_low": 8.8,
        "market_cap": 138.7,
        "daily_volume": 11.0,
        "sector": "醫療",
        "dividend_yield": 6.2,
        "risk_level": "中低",
        "recommendation": ""
      },
      {
        "ticker": "MRK",
        "name": "Merck",
        "pe_ratio": 8.8,
        "current_price": 65.5,
        "low_52w": 60.2,
        "distance_from_low": 8.8,
        "market_cap": 280.5,
        "daily_volume": 9.5,
        "sector": "醫療",
        "dividend_yield": 3.8,
        "risk_level": "低",
        "recommendation": "優先推薦"
      }
    ],
    "momentumStocks": [
      {
        "ticker": "LLY",
        "name": "禮來",
        "five_day_return": 10.9,
        "rsi_14": 68.5,
        "roc_14": 12.5,
        "roc_21": 18.2,
        "status": "超買接近",
        "outlook": "謹慎",
        "trend": "高於所有均線"
      },
      {
        "ticker": "CSCO",
        "name": "Cisco",
        "five_day_return": 9.8,
        "rsi_14": 65.2,
        "roc_14": 10.8,
        "roc_21": 15.3,
        "status": "超買接近",
        "outlook": "謹慎",
        "trend": "高於50/200MA"
      },
      {
        "ticker": "MRK",
        "name": "Merck",
        "five_day_return": 7.7,
        "rsi_14": 62.8,
        "roc_14": 9.5,
        "roc_21": 13.8,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "ABBV",
        "name": "AbbVie",
        "five_day_return": 6.0,
        "rsi_14": 58.9,
        "roc_14": 7.2,
        "roc_21": 10.5,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "AMD",
        "name": "AMD",
        "five_day_return": 5.7,
        "rsi_14": 61.5,
        "roc_14": 8.9,
        "roc_21": 12.4,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於50/200MA"
      },
      {
        "ticker": "DHR",
        "name": "Danaher",
        "five_day_return": 5.4,
        "rsi_14": 59.2,
        "roc_14": 6.6,
        "roc_21": 9.4,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於20/50MA"
      },
      {
        "ticker": "COP",
        "name": "ConocoPhillips",
        "five_day_return": 5.2,
        "rsi_14": 58.7,
        "roc_14": 7.1,
        "roc_21": 10.2,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "GILD",
        "name": "吉利德科學",
        "five_day_return": 5.2,
        "rsi_14": 57.3,
        "roc_14": 6.3,
        "roc_21": 9.1,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於50/200MA"
      },
      {
        "ticker": "AMGN",
        "name": "Amgen",
        "five_day_return": 5.2,
        "rsi_14": 56.8,
        "roc_14": 5.8,
        "roc_21": 8.3,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於所有均線"
      },
      {
        "ticker": "NKE",
        "name": "Nike",
        "five_day_return": 5.0,
        "rsi_14": 54.2,
        "roc_14": 5.2,
        "roc_21": 7.5,
        "status": "中性",
        "outlook": "樂觀",
        "trend": "高於20/50MA"
      }
    ]
  }
];
